version: '2.4'
services:
  search:
    image: codelibs/fess:fess12.4.3
    working_dir: /usr/share/fess
    ports:
      - 8080:8080
      - 9200:9200
      - 9300:9300
#    sysctls:
#        - vm.max_map_count=262144
#    privileged: true
    command: /usr/share/fess/run.sh
    volumes:
      - ./run.sh:/usr/share/fess/run.sh
      - ./conf/fess_config.properties:/etc/fess/fess_config.properties
      - ./conf/doc.json:/usr/share/fess/app/WEB-INF/classes/fess_indices/fess/doc.json
      - ./conf/admin_searchlist_edit.jsp:/usr/share/fess/app/WEB-INF/view/admin/searchlist/admin_searchlist_edit.jsp
      - ./data/config:/var/lib/elasticsearch/config
      - ./data:/var/lib/elasticsearch
      #config_sync (./config) and nodes

